In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pickle
import os

In [2]:
dataOutput = '/home/olivia/mothPruning/mothMachineLearning_dataAndFigs/DataOutput/Experiments/'
modelsubdir = '2022_01_04__04_18_29'

historyFile = 'meanHistory.pkl'
meanHistory = pickle.load(open(os.path.join(dataOutput, modelsubdir,  'preprocessedNets', historyFile), 'rb'))

weightsFile = 'weights.pkl'
weights = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', weightsFile), 'rb'))

biasesFile = 'biases.pkl'
biases = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', biasesFile), 'rb'))

masksFile = 'masks.pkl'
masks = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', masksFile), 'rb'))
                    
networksFile = 'networks.pkl'
networks = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', networksFile), 'rb'))

lossesFile = 'pruneLosses.pkl'
losses = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', lossesFile), 'rb'))

In [3]:
losses = np.array(losses).T

In [4]:
threshold = 0.001
sparseNetworks = []


for i in range(len(losses)):
    indices = np.flatnonzero(losses[i] <= threshold)
    print(indices)
    if len(indices) != 0:
        index = indices[-1]
        print(index)
        sparseNet = (index, networks[i][index])
        sparseNetworks.append(sparseNet)
        
    else: 
        print("skipped")

[6 7]
7
[]
skipped
[ 2  3  4  5  6  7  8 10 11]
11
[]
skipped
[6 7]
7
[5 6 7]
7
[ 3  4  5  6  7  8  9 10 11 12 13]
13
[]
skipped
[5 6]
6
[4 5 6 7]
7


In [5]:
len(sparseNetworks)

7

In [6]:
pickle.dump(sparseNetworks, open(os.path.join(dataOutput, modelsubdir, 'sparseNetworks.pkl'), 'wb'))