In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pickle
import os

In [8]:
dataOutput = '/home/olivia/mothPruning/mothMachineLearning_dataAndFigs/DataOutput/Experiments/pruned_bias/'
modelsubdir = '2022_11_05__01_04_10'

historyFile = 'meanHistory.pkl'
meanHistory = pickle.load(open(os.path.join(dataOutput, modelsubdir,  'preprocessedNets', historyFile), 'rb'))

weightsFile = 'weights.pkl'
weights = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', weightsFile), 'rb'))

biasesFile = 'biases.pkl'
biases = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', biasesFile), 'rb'))

masksFile = 'masks.pkl'
masks = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', masksFile), 'rb'))

bmasksFile = 'bmasks.pkl'
bmasks = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', bmasksFile), 'rb'))
                    
networksFile = 'networks.pkl'
networks = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', networksFile), 'rb'))

lossesFile = 'pruneLosses.pkl'
losses = pickle.load(open(os.path.join(dataOutput, modelsubdir, 'preprocessedNets', lossesFile), 'rb'))

In [9]:
losses = np.array(losses).T

In [10]:
threshold = 0.001
sparseNetworks = []


for i in range(len(losses)):
    indices = np.flatnonzero(losses[i] <= threshold)
    print(indices)
    if len(indices) != 0:
        index = indices[-1]
        print(index)
        sparseNet = (index, networks[i][index])
        sparseNetworks.append(sparseNet)
        
    else: 
        print("skipped")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10]
10
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10 11]
11
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10]
10
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10]
10
[ 0  1  2  3  4  5  6  7  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10 11]
11
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10 11]
11
[ 0  1  2  3  4  5  6  7  8 10]
10
[ 0  1  2  3  4  5  6  7  8  9 10 11]
11
[0 1 2 3 4 5 6 7]
7
[ 0  1  2  3  4  5  6  7  9 10]
10
[ 0  1  2  3  4  5  6  7  9 10]
10
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
12
[ 0  1  2  3  4  5  6  7  8 

In [11]:
len(sparseNetworks)

400

In [12]:
pickle.dump(sparseNetworks, open(os.path.join(dataOutput, modelsubdir, 'sparseNetworks.pkl'), 'wb'))